### PR TITLE
Import Pulseaudio changes in Xenial up to version 1:8.0-0ubuntu3.10

### PR DESCRIPTION
**Pull request by peat-psuwit**
This PR brings updates to Pulseaudio in Xenial to UBports. For us, this primarily improves the experience of using Bluetooth headset. I've also added a patch which should fix the reported regression from these changes (ubports/ubuntu-touch#528).

I've tested these changes on the Halium 7.1 port of FP2. However, there's a patch that affects the droid module, and I can't test that because the in-tree module doesn't support the 7.1-based port. So, testing on older devices is required.

This PR comes with Jenkinsfile update.

Test plan: https://wiki.ubuntu.com/Process/Merges/TestPlan/pulseaudio

### CODE REVIEW

**Comment by Flohack74** [comment]
If you like I can test with OPO, FP2, N5, E5 with an old crappy BT headset ;)

**Comment by peat-psuwit** [comment]
@Flohack74 That would be great, thanks.

The primary cause of the mentioned regression seems to be the Bluetooth card's profile in PA. If it doesn't work, please capture the result of `pacmd list-cards` for the Bluetooth card.

**Comment by Flohack74** [comment]
Ok tell me concrete test cases: calls or music or both? :)

**Comment by Flohack74** [comment]
I tested today following the Canonical checklist. Basically I came to the point of the call, up to that everything was fine. Music app was stopped before calling. After the call however, I could not hear anything anymore when starting to play in music app. Also another call did not get Audio back. The volume control did not show bluetooth headset anymore but loudspeaker. So, I will try to reproduce, but it seems a call destroys music playback.

This test was done on OPO. Which has ofc classic port with 5.1. The improvement however is that before this patch calling did not work, either send or receive audio was failing. So, for calls its definitely a good PR ^

**Comment by peat-psuwit** [comment]
There's a report of possible regression from an E4.5 user in my forum post. I'll have to investigate further.

**Review by UniversalSuperBox — APPROVED** [review]
The final device we had concerns with for this PR was the Nexus 5. However, in my testing this does not cause noticeable regressions from our previous PulseAudio version. Allow me to explain...

In https://forums.ubports.com/topic/4300/call-for-testing-updated-pulseaudio-better-bluetooth-headset-support, we've received complaints of **very loud** calls. I've successfully reproduced this issue on my Nexus 5. However, this occurs with or without the `xenial_-_pulseaudio-updates-to-0ubuntu3.10` repository installed. Therefore, it is not a regression.

A similar issue was experienced on the Pro 5, where call audio with this patch was very loud or cutting out altogether. I believe that "Cutting out" may actually be peaking the user's headphones, with the headphones stopping their audio output. However, this is not noticeably worse than the old behavior, where call audio would stop entirely after a second or so for these users. Therefore, also not a regression. Just something to look into in the future.

An additional problem noticed by users was issues with Bluetooth reconnections during audio playback. If a Bluetooth audio device disconnected, playback would never go to a Bluetooth audio device again. This is an issue both before and after this update as well, and therefore not a regression.

With all of this in mind, I think it is time to merge this for further testing pending OTA-13.

**Comment by Flohack74** [comment]
Just quick question, @UniversalSuperBox you said that basically no regressions have appeared, but actually what should be the improvement, if also none of the old issues is fixed? @peat-psuwit wrote in the first comment about BT headset experience that will be improved. I am missing a bit a description what the people should really look for during testing, except no regressions :)

**Comment by jezek** [comment]
There is a call for testing. How do we test this, please?

**Comment by peat-psuwit** [comment]
Please follow the test plan linked in the description.

**Comment by Bolly** [comment]
> Please follow the test plan linked in the description.

Checked this on a BQM10FHD running RC 2020 W-36.

- Check that there's a default card provided by the droid module ✔
- Import audio/video files into your phone, and try playing them using the music-app/mediaplayer-app ✔
- Testing basic audio recording with parecord and paplay: ✔
- Check that the sink-input used by media-hub when playing via music-app/mediaplayer-app has the multimedia media role ✔
- Check that the sink-input used by media-hub when playing ringtone/notification has the alert media role ✔
- Check that the sink-input used by media-hub when playing alarm has the alarm media role ✔
- Check that there is sink-input using the phone media role when a call is active  📵 (Tablet, no phone)
- Play an audio using the music-app and start a call. The audio from the music-app should be corked while the phone call is active. 📵 (Tablet, no phone)
- Play an audio/video using the webbrowser and trigger an alarm. The audio from the webbrowser should be corked while the alarm call is active. ✔
- Play an audio/video using the webbrowser and trigger a ringtone/notification. The audio from the webbrowser should be reduced (ducking effect) while the ringtone/notification is active. ✔

- Play a song with music-app and connect a bluetooth device (with A2DP). The audio from music-app should automatically move to the bluetooth device. ❌

It works the first time, the second time it doesn't. I can see the notification but does not route the audio to the handset.
I think this was already happening, I think nothing has been broken.

- While playing a song with a bluetooth device connected, turn the bluetooth device off. The audio from music-app should automatically move to the internal speaker. 🤔

The audio is paused. In my opinion it's fine like that.

**Comment by jezek** [comment]
Tests answered in https://github.com/ubports/pulseaudio-modules-droid/pull/6#issuecomment-690421302

**Pull request merged**
